//! Keycode mapping from winit to Android AKEYCODE

use winit::keyboard::KeyCode;

/// Map winit KeyCode to Android AKEYCODE
#[allow(dead_code)]
pub fn map_keycode(keycode: KeyCode) -> Option<i32> {
    Some(match keycode {
        // Letters
        KeyCode::KeyA => 29,
        KeyCode::KeyB => 30,
        KeyCode::KeyC => 31,
        KeyCode::KeyD => 32,
        KeyCode::KeyE => 33,
        KeyCode::KeyF => 34,
        KeyCode::KeyG => 35,
        KeyCode::KeyH => 36,
        KeyCode::KeyI => 37,
        KeyCode::KeyJ => 38,
        KeyCode::KeyK => 39,
        KeyCode::KeyL => 40,
        KeyCode::KeyM => 41,
        KeyCode::KeyN => 42,
        KeyCode::KeyO => 43,
        KeyCode::KeyP => 44,
        KeyCode::KeyQ => 45,
        KeyCode::KeyR => 46,
        KeyCode::KeyS => 47,
        KeyCode::KeyT => 48,
        KeyCode::KeyU => 49,
        KeyCode::KeyV => 50,
        KeyCode::KeyW => 51,
        KeyCode::KeyX => 52,
        KeyCode::KeyY => 53,
        KeyCode::KeyZ => 54,
        // Numbers
        KeyCode::Digit0 => 7,
        KeyCode::Digit1 => 8,
        KeyCode::Digit2 => 9,
        KeyCode::Digit3 => 10,
        KeyCode::Digit4 => 11,
        KeyCode::Digit5 => 12,
        KeyCode::Digit6 => 13,
        KeyCode::Digit7 => 14,
        KeyCode::Digit8 => 15,
        KeyCode::Digit9 => 16,
        // Special keys
        KeyCode::Space => 62,
        KeyCode::Enter => 66,
        KeyCode::Backspace => 67,
        KeyCode::Delete => 112,
        KeyCode::Tab => 61,
        KeyCode::Escape => 111,
        // Navigation
        KeyCode::ArrowUp => 19,
        KeyCode::ArrowDown => 20,
        KeyCode::ArrowLeft => 21,
        KeyCode::ArrowRight => 22,
        KeyCode::Home => 122,
        KeyCode::End => 123,
        KeyCode::PageUp => 92,
        KeyCode::PageDown => 93,
        // Modifiers
        KeyCode::ShiftLeft => 59,
        KeyCode::ShiftRight => 60,
        KeyCode::ControlLeft => 113,
        KeyCode::ControlRight => 114,
        KeyCode::AltLeft => 57,
        KeyCode::AltRight => 58,
        // Punctuation
        KeyCode::Comma => 55,
        KeyCode::Period => 56,
        KeyCode::Slash => 76,
        KeyCode::Semicolon => 74,
        KeyCode::Quote => 75,
        KeyCode::BracketLeft => 71,
        KeyCode::BracketRight => 72,
        KeyCode::Backslash => 73,
        KeyCode::Minus => 69,
        KeyCode::Equal => 70,
        KeyCode::Backquote => 68,
        // Function keys
        KeyCode::F1 => 131,
        KeyCode::F2 => 132,
        KeyCode::F3 => 133,
        KeyCode::F4 => 134,
        KeyCode::F5 => 135,
        KeyCode::F6 => 136,
        KeyCode::F7 => 137,
        KeyCode::F8 => 138,
        KeyCode::F9 => 139,
        KeyCode::F10 => 140,
        KeyCode::F11 => 141,
        KeyCode::F12 => 142,
        _ => return None,
    })
}
